---
- name: find existing vhost files
  ansible.builtin.find:
    paths: "{{ __nginx_vhosts_path }}"
    patterns: "*.conf"
    depth: 1
  register: found_vhost_files

- name: remove unmanaged vhosts files
  ansible.builtin.file:
    path: "{{ item }}"
    state: absent
  notify: reload nginx
  loop: "{{
      found_vhost_files.files|map(attribute='path')
      | difference(managed_config_files.results|map(attribute='dest'))
      | difference(nginx_unmanaged_configs_allowlist|map('regex_replace', '^', __nginx_vhosts_path ~ '/'))
    }}"
