---
dependency:
  name: galaxy
  options:
    role-file: requirements.yml
    requirements-file: requirements.yml
driver:
  name: vagrant
platforms:
  - name: molecule-nginx-debian11-$TOX_ENVNAME
    box: debian/bullseye64
    memory: 384
    cpus: 1

  - name: molecule-nginx-centosstream8-$TOX_ENVNAME
    box: bento/centos-stream-8
    memory: 384
    cpus: 1

  - name: molecule-nginx-archlinux-$TOX_ENVNAME
    box: archlinux/archlinux
    memory: 384
    cpus: 1
provisioner:
  name: ansible
  lint: ansible-lint --force-color
lint: |
  set -e
  yamllint .
  ansible-lint
verifier:
  name: ansible
