---
- name: Verify
  hosts: all
  become: true
  tasks:
    - name: gather package facts
      ansible.builtin.package_facts:

    - name: check if Nginx is installed
      ansible.builtin.assert:
        that: "'nginx' in ansible_facts.packages"

    - name: gather service facts
      ansible.builtin.service_facts:

    - name: check if services are enabled and running
      ansible.builtin.assert:
        that:
          - "'nginx.service' in ansible_facts.services"
          - "ansible_facts.services['nginx.service'].state == 'running'"
          - "ansible_facts.services['nginx.service'].status == 'enabled'"

    - name: assert website is delivered
      ansible.builtin.uri:
        url: http://127.0.0.1
        return_content: true
        status_code: [200]
      register: website
      failed_when: "'Hello World!' not in website.content"

    - name: get stat of superfluous config file
      ansible.builtin.stat:
        path: /etc/nginx/conf.d/superfluous.conf
      register: superfluous_config

    - name: ensure superfluous config was removed
      ansible.builtin.assert:
        that: not superfluous_config.stat.exists
